keys:
  - &users:
    - &quil age1negtdklqh4uav50q2aw59tcc0kv07zuqckuvksag89tsyfuz75ms7gdqg6
  - &hosts:
    - &snowflake age1jz5wv7c5k9snnw60uaw5srft5dsaaqccvqu42s9mxy2dhwem99qq6fy6qh
  - &admin age1pfjguamx2gdq9f9ksch2xr6cgjxgmcc8vw5jjyhdsrhy7787jdkqxgvqel
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *quil
      - *snowflake
      - *admin
