{
  pkgs,
  inputs,
  system,
  config,
  ...
}:
{
  home.packages = [
    inputs.quickshell.packages.${system}.default
    pkgs.jq # json parsing
    pkgs.playerctl
  ];

  xdg = {
    desktopEntries."org.quickshell" = {
      name = "Quickshell";
      exec = "quickshell";
      noDisplay = true;
    };
    configFile = {
      # Main bar config
      "quickshell/bar.qml".source = ./bar.qml;
      
      # Module files
      "quickshell/Modules/qmldir".source = ./Modules/qmldir;
      "quickshell/Modules/Theme.qml".text = with config.lib.stylix.colors.withHashtag; ''
        pragma Singleton
        import QtQuick

        QtObject {
            // Base16 Color Scheme (generated by Stylix)
            readonly property color base00: "${base00}"
            readonly property color base01: "${base01}"
            readonly property color base02: "${base02}"
            readonly property color base03: "${base03}"
            readonly property color base04: "${base04}"
            readonly property color base05: "${base05}"
            readonly property color base06: "${base06}"
            readonly property color base07: "${base07}"
            readonly property color base08: "${base08}"
            readonly property color base09: "${base09}"
            readonly property color base0A: "${base0A}"
            readonly property color base0B: "${base0B}"
            readonly property color base0C: "${base0C}"
            readonly property color base0D: "${base0D}"
            readonly property color base0E: "${base0E}"
            readonly property color base0F: "${base0F}"

            // Alert Colors
            readonly property color alertColor: "${base08}"

            // Typography
            readonly property string fontFamily: "Iosevka Nerd Font"
            readonly property int fontSize: 16
        }
      '';
      "quickshell/Modules/CpuWidget.qml".source = ./Modules/CpuWidget.qml;
      "quickshell/Modules/MemoryWidget.qml".source = ./Modules/MemoryWidget.qml;
      "quickshell/Modules/TemperatureWidget.qml".source = ./Modules/TemperatureWidget.qml;
      "quickshell/Modules/BrightnessWidget.qml".source = ./Modules/BrightnessWidget.qml;
      "quickshell/Modules/VolumeWidget.qml".source = ./Modules/VolumeWidget.qml;
      "quickshell/Modules/MusicWidget.qml".source = ./Modules/MusicWidget.qml;
      "quickshell/Modules/MusicPopup.qml".source = ./Modules/MusicPopup.qml;
      "quickshell/Modules/NetworkWidget.qml".source = ./Modules/NetworkWidget.qml;
      "quickshell/Modules/NetworkPopup.qml".source = ./Modules/NetworkPopup.qml;
      "quickshell/Modules/NetworkSelector.qml".source = ./Modules/NetworkSelector.qml;
      "quickshell/Modules/WindowWidget.qml".source = ./Modules/WindowWidget.qml;
      "quickshell/Modules/Workspaces.qml".source = ./Modules/Workspaces.qml;
      "quickshell/Modules/Clock.qml".source = ./Modules/Clock.qml;
      "quickshell/Modules/Spacer.qml".source = ./Modules/Spacer.qml;
    };
  };
}
