{
  pkgs,
  inputs,
  system,
  config,
  ...
}:
{
  home.packages = [
    inputs.quickshell.packages.${system}.default
    pkgs.jq # json parsing
    pkgs.playerctl
  ];

  xdg = {
    desktopEntries."org.quickshell" = {
      name = "Quickshell";
      exec = "quickshell";
      noDisplay = true;
    };
    configFile = {
      # Main bar config
      "quickshell/bar.qml".source = ./bar.qml;
      
      # Module files
      "quickshell/Modules/qmldir".source = ./Modules/qmldir;
      "quickshell/Modules/Theme.qml".text = with config.lib.stylix.colors.withHashtag; ''
        pragma Singleton
        import QtQuick

        QtObject {
            // Base16 Color Scheme (generated by Stylix)
            readonly property color base00: "${base00}"
            readonly property color base01: "${base01}"
            readonly property color base02: "${base02}"
            readonly property color base03: "${base03}"
            readonly property color base04: "${base04}"
            readonly property color base05: "${base05}"
            readonly property color base06: "${base06}"
            readonly property color base07: "${base07}"
            readonly property color base08: "${base08}"
            readonly property color base09: "${base09}"
            readonly property color base0A: "${base0A}"
            readonly property color base0B: "${base0B}"
            readonly property color base0C: "${base0C}"
            readonly property color base0D: "${base0D}"
            readonly property color base0E: "${base0E}"
            readonly property color base0F: "${base0F}"

            // Alert Colors
            readonly property color alertColor: "#CD5C5C"
            readonly property color successColor: "#7ec699"
            readonly property color warningColor: "#e5c07b"
            readonly property color blueColor: "#61afef"
            readonly property color orangeColor: "#d19a66"

            // Typography
            readonly property string fontFamily: "Iosevka Nerd Font"
            readonly property int fontSize: 16
            
            // Gradient color function for usage stats (0-100): green → yellow → red
            function usageColor(value) {
                if (value < 50) {
                    // Green to Yellow (0-50)
                    var t = value / 50;
                    return Qt.rgba(
                        0.49 + t * 0.4,  // R: 0.49 → 0.89
                        0.78 - t * 0.03, // G: 0.78 → 0.75
                        0.60 - t * 0.12, // B: 0.60 → 0.48
                        1
                    );
                } else {
                    // Yellow to Red (50-100)
                    var t2 = (value - 50) / 50;
                    return Qt.rgba(
                        0.89 - t2 * 0.09, // R: 0.89 → 0.80
                        0.75 - t2 * 0.39, // G: 0.75 → 0.36
                        0.48 - t2 * 0.12, // B: 0.48 → 0.36
                        1
                    );
                }
            }
            
            // Gradient color function for temperature: blue → orange → red
            function tempColor(value) {
                if (value < 50) {
                    return blueColor;
                } else if (value < 70) {
                    // Blue to Orange (50-70)
                    var t = (value - 50) / 20;
                    return Qt.rgba(
                        0.38 + t * 0.44, // R: 0.38 → 0.82
                        0.69 - t * 0.09, // G: 0.69 → 0.60
                        0.94 - t * 0.54, // B: 0.94 → 0.40
                        1
                    );
                } else {
                    // Orange to Red (70-100)
                    var t2 = (value - 70) / 30;
                    return Qt.rgba(
                        0.82 - t2 * 0.02, // R: 0.82 → 0.80
                        0.60 - t2 * 0.24, // G: 0.60 → 0.36
                        0.40 - t2 * 0.04, // B: 0.40 → 0.36
                        1
                    );
                }
            }
        }
      '';
      "quickshell/Modules/CpuWidget.qml".source = ./Modules/CpuWidget.qml;
      "quickshell/Modules/MemoryWidget.qml".source = ./Modules/MemoryWidget.qml;
      "quickshell/Modules/TemperatureWidget.qml".source = ./Modules/TemperatureWidget.qml;
      "quickshell/Modules/BrightnessWidget.qml".source = ./Modules/BrightnessWidget.qml;
      "quickshell/Modules/VolumeWidget.qml".source = ./Modules/VolumeWidget.qml;
      "quickshell/Modules/MusicWidget.qml".source = ./Modules/MusicWidget.qml;
      "quickshell/Modules/MusicPopup.qml".source = ./Modules/MusicPopup.qml;
      "quickshell/Modules/NetworkWidget.qml".source = ./Modules/NetworkWidget.qml;
      "quickshell/Modules/NetworkPopup.qml".source = ./Modules/NetworkPopup.qml;
      "quickshell/Modules/NetworkSelector.qml".source = ./Modules/NetworkSelector.qml;
      "quickshell/Modules/WindowWidget.qml".source = ./Modules/WindowWidget.qml;
      "quickshell/Modules/Workspaces.qml".source = ./Modules/Workspaces.qml;
      "quickshell/Modules/Clock.qml".source = ./Modules/Clock.qml;
      "quickshell/Modules/Spacer.qml".source = ./Modules/Spacer.qml;
      # New modules
      "quickshell/Modules/BatteryWidget.qml".source = ./Modules/BatteryWidget.qml;
      "quickshell/Modules/BatteryPopup.qml".source = ./Modules/BatteryPopup.qml;
      "quickshell/Modules/BluetoothWidget.qml".source = ./Modules/BluetoothWidget.qml;
      "quickshell/Modules/BluetoothPopup.qml".source = ./Modules/BluetoothPopup.qml;
      "quickshell/Modules/PowerMenu.qml".source = ./Modules/PowerMenu.qml;
      "quickshell/Modules/KeyboardWidget.qml".source = ./Modules/KeyboardWidget.qml;
      "quickshell/Modules/CalendarPopup.qml".source = ./Modules/CalendarPopup.qml;
      "quickshell/Modules/WeatherWidget.qml".source = ./Modules/WeatherWidget.qml;
      "quickshell/Modules/WeatherPopup.qml".source = ./Modules/WeatherPopup.qml;
      "quickshell/Modules/NotificationPopup.qml".source = ./Modules/NotificationPopup.qml;
      "quickshell/Modules/NotificationToast.qml".source = ./Modules/NotificationToast.qml;
      "quickshell/Modules/BarIcon.qml".source = ./Modules/BarIcon.qml;
      "quickshell/Modules/MiniProgress.qml".source = ./Modules/MiniProgress.qml;
      "quickshell/Modules/AppLauncher.qml".source = ./Modules/AppLauncher.qml;
    };
  };
}
