#!/usr/bin/env python3
import os
import sys
import argparse
import colorsys
import subprocess
import shutil
from pathlib import Path

DEFAULT_BASE16 = {
    "base00": "#16181c",
    "base01": "#1f2227",
    "base02": "#282c33",
    "base03": "#504945",
    "base04": "#bdae93",
    "base05": "#d5c4a1",
    "base06": "#ebdbb2",
    "base07": "#fbf1c7",
    "base08": "#fb4934",
    "base09": "#fe8019",
    "base0A": "#fabd2f",
    "base0B": "#b8bb26",
    "base0C": "#8ec07c",
    "base0D": "#83a598",
    "base0E": "#d3869b",
    "base0F": "#d65d0e",
}

CSS_TEMPLATE = """/* Generated by generate_waybar_stylix.py */
@define-color red       #cc241d;
@define-color green     #98971a;
@define-color yellow    #d79921;
@define-color blue      #458588;
@define-color purple    #b16286;
@define-color aqua      #689d6a;
@define-color gray      #a89984;
@define-color brgray    #928374;
@define-color brred     #fb4934;
@define-color brgreen   #b8bb26;
@define-color bryellow  #fabd2f;
@define-color brblue    #83a598;
@define-color brpurple  #d3869b;
@define-color braqua    #8ec07c;
@define-color orange    #d65d0e;
@define-color brorange  #fe8019;

* {{
  border: none;
  font-size: 14px;
  border-radius: 5px;
}}

window#waybar {{
  background-color: transparent;
}}

tooltip {{
  font-family: Iosevka Nerd Font Propo, monospace;
  background-color: {base02};
  background: {base01};
  border-radius: 5px;
  border: 1px solid {base02};
}}

tooltip label {{
  color: {base04};
  text-shadow: none;
}}

.modules-right {{
  margin: 10px 10px 0 0;
}}
.modules-center {{
  margin: 10px 0 0 0;
}}
.modules-left {{
  margin: 10px 0 0 10px;
}}

#workspaces {{
  background-color: {base01};
}}

#workspaces button {{
  padding: 0 5px;
  color: {base04};
  border-radius: 0;
}}

#workspaces button:first-child {{
  border-radius: 5px 0 0 5px;
}}

#workspaces button:last-child {{
  border-radius: 0 5px 5px 0;
}}

#workspaces button:first-child:last-child {{
  border-radius: 5px;
}}

#workspaces button:hover {{
  color: {base04};
}}

#workspaces button.focused {{
  background-color: {base0D};
}}

#workspaces button.occupied {{
  border-bottom: 1.5px solid {base05};
}}

#workspaces button.urgent {{
  background-color: {base08};
}}

#idle_inhibitor,
#cava,
#scratchpad,
#mode,
#window,
#clock,
#battery,
#backlight,
#custom-weather,
#wireplumber,
#tray,
#mpris,
#load {{
  padding: 0 10px;
  background-color: {base01};
  color: {base04};
}}

#mode {{
  background-color: @aqua;
  color: {base01};
}}

/* If workspaces is the leftmost module, omit left margin */
.modules-left > widget:first-child > #workspaces {{
  margin-left: 0;
}}

/* If workspaces is the rightmost module, omit right margin */
.modules-right > widget:last-child > #workspaces {{
  margin-right: 0;
}}

#cava {{
  padding: 0 5px;
}}

#battery.charging, #battery.plugged {{
  background-color: @green;
  color: {base01};
}}

@keyframes blink {{
  to {{
    background-color: {base01};
    color: {base04};
  }}
}}

/* Using steps() instead of linear as a timing function to limit cpu usage */
#battery.critical:not(.charging) {{
  background-color: @red;
  color: {base01};
  animation-name: blink;
  animation-duration: 0.5s;
  animation-timing-function: steps(12);
  animation-iteration-count: infinite;
  animation-direction: alternate;
}}

#wireplumber.muted {{
  background-color: @red;
  color: {base05};
}}

#tray > .passive {{
  -gtk-icon-effect: dim;
}}

#tray > .needs-attention {{
  -gtk-icon-effect: highlight;
}}

#mpris.playing {{
  background-color: {base01};
}}

#tray menu {{
  font-family: sans-serif;
}}

#scratchpad.empty {{
  background: transparent;
  padding: 0;
}}

#cpu {{
  background-color: {base01};
}}

#memory {{
  background-color: {base01};
}}

#temperature {{
  background-color: {base01};
}}
"""

def relative_luminance(hex_str):
    try:
        hex_str = hex_str.lstrip('#')
        r, g, b = int(hex_str[0:2], 16), int(hex_str[2:4], 16), int(hex_str[4:6], 16)
        adjust = lambda c: (c / 255.0) / 12.92 if (c / 255.0) <= 0.03928 else (((c / 255.0) + 0.055) / 1.055) ** 2.4
        return 0.2126 * adjust(r) + 0.7152 * adjust(g) + 0.0722 * adjust(b)
    except Exception:
        return 0.5

def get_contrast(hex1, hex2):
    l1 = relative_luminance(hex1)
    l2 = relative_luminance(hex2)
    return (max(l1, l2) + 0.05) / (min(l1, l2) + 0.05)

def ensure_min_contrast(hex_str, bg_hex, target_contrast=4.5):
    if get_contrast(hex_str, bg_hex) >= target_contrast:
        return hex_str
    try:
        hex_clean = hex_str.lstrip('#')
        r, g, b = int(hex_clean[0:2], 16), int(hex_clean[2:4], 16), int(hex_clean[4:6], 16)
        h, s, v = colorsys.rgb_to_hsv(r / 255.0, g / 255.0, b / 255.0)
        
        for _ in range(25):
            v = min(1.0, v + 0.04)
            if v > 0.70:
                s = max(0.0, s - 0.04)
            r_n, g_n, b_n = [int(x * 255) for x in colorsys.hsv_to_rgb(h, s, v)]
            candidate = f"#{r_n:02x}{g_n:02x}{b_n:02x}"
            if get_contrast(candidate, bg_hex) >= target_contrast:
                return candidate
    except Exception:
        pass
    return "#e5e9f0"

def get_hsv_v(hex_str):
    try:
        hex_clean = hex_str.lstrip('#')
        r, g, b = int(hex_clean[0:2], 16), int(hex_clean[2:4], 16), int(hex_clean[4:6], 16)
        _, _, v = colorsys.rgb_to_hsv(r / 255.0, g / 255.0, b / 255.0)
        return v
    except Exception:
        return 0.5

def darken_color(hex_str, factor=0.55, max_v=0.12):
    try:
        hex_clean = hex_str.lstrip('#')
        r, g, b = int(hex_clean[0:2], 16), int(hex_clean[2:4], 16), int(hex_clean[4:6], 16)
        h, s, v = colorsys.rgb_to_hsv(r / 255.0, g / 255.0, b / 255.0)
        new_v = min(v * factor, max_v)
        r_n, g_n, b_n = [int(x * 255) for x in colorsys.hsv_to_rgb(h, s, new_v)]
        return f"#{r_n:02x}{g_n:02x}{b_n:02x}"
    except Exception:
        return "#16181c"

def extract_base16(image_path):
    """Extract a well-balanced, WCAG-contrast guaranteed base16 palette from an image using Pillow."""
    try:
        from PIL import Image
        img = Image.open(image_path).convert("RGB")
        img.thumbnail((200, 200))
        quantized = img.quantize(colors=24)
        palette_raw = quantized.getpalette()[:72]
        colors = []
        seen = set()
        for i in range(0, len(palette_raw), 3):
            r, g, b = palette_raw[i:i+3]
            hex_val = f"#{r:02x}{g:02x}{b:02x}"
            if hex_val in seen:
                continue
            seen.add(hex_val)
            h, s, v = colorsys.rgb_to_hsv(r / 255.0, g / 255.0, b / 255.0)
            colors.append({
                "rgb": (r, g, b),
                "hex": hex_val,
                "h": h, "s": s, "v": v
            })
        
        # Sort colors by brightness/value (darkest to lightest)
        colors.sort(key=lambda c: c["v"])

        # Base00 (darkest bg / terminal bg), Base01 (panel bg) & Base02 (selection)
        base00 = darken_color(colors[0]["hex"], factor=0.55, max_v=0.12)
        base01 = darken_color(colors[min(1, len(colors)-1)]["hex"], factor=0.70, max_v=0.16)
        base02 = darken_color(colors[min(2, len(colors)-1)]["hex"], factor=0.80, max_v=0.22)

        # Foreground candidates (lightest colors sorted by brightness)
        fg_candidates = [c for c in colors if c["v"] >= 0.4]
        if not fg_candidates:
            fg_candidates = colors[max(0, len(colors)-6):]
        fg_candidates.sort(key=lambda c: c["v"], reverse=True)

        base07 = fg_candidates[0]["hex"]
        base06 = fg_candidates[min(1, len(fg_candidates)-1)]["hex"]
        base05 = fg_candidates[min(2, len(fg_candidates)-1)]["hex"]
        base04 = fg_candidates[min(3, len(fg_candidates)-1)]["hex"]
        base03 = fg_candidates[min(4, len(fg_candidates)-1)]["hex"] if len(fg_candidates) > 4 else colors[min(3, len(colors)-1)]["hex"]

        # Guarantee high contrast against panel background (base01)
        base03 = ensure_min_contrast(base03, base01, target_contrast=3.5) # Inactive workspace numbers / muted icons
        base04 = ensure_min_contrast(base04, base01, target_contrast=4.5) # Subtitles / secondary labels
        base05 = ensure_min_contrast(base05, base01, target_contrast=6.5) # Main text
        base06 = ensure_min_contrast(base06, base01, target_contrast=8.5) # Light text
        base07 = ensure_min_contrast(base07, base01, target_contrast=10.0) # Brightest text

        # Accent candidates MUST NOT be dark background colors (v >= 0.35)
        accents = [c for c in colors if c["v"] >= 0.35]
        if len(accents) < 4:
            accents = colors[min(2, len(colors)-1):]
        
        # Sort accents by vibrancy (saturation & brightness)
        accents.sort(key=lambda c: (c["s"] * 0.7 + c["v"] * 0.3), reverse=True)

        # Primary Accent (base0D - active workspace/highlight): cool blueish or most vibrant bright color
        blues = [c for c in accents if 0.5 <= c["h"] <= 0.7]
        base0D = blues[0]["hex"] if blues else accents[0]["hex"]

        # Red/Urgent Accent (base08): red/pinkish hue or top vibrant accent
        reds = [c for c in accents if c["h"] <= 0.08 or c["h"] >= 0.90]
        base08 = reds[0]["hex"] if reds else (accents[min(1, len(accents)-1)]["hex"] if len(accents) > 1 else accents[0]["hex"])

        # Yellow/Warning (base0A):
        yellows = [c for c in accents if 0.10 <= c["h"] <= 0.22]
        base0A = yellows[0]["hex"] if yellows else accents[min(2, len(accents)-1)]["hex"]

        # Green/Success (base0B):
        greens = [c for c in accents if 0.22 < c["h"] <= 0.45]
        base0B = greens[0]["hex"] if greens else accents[min(3, len(accents)-1)]["hex"]

        # Aqua/Cyan (base0C):
        cyans = [c for c in accents if 0.45 < c["h"] < 0.55]
        base0C = cyans[0]["hex"] if cyans else accents[min(4, len(accents)-1)]["hex"]

        # Orange (base09):
        oranges = [c for c in accents if 0.05 <= c["h"] <= 0.12]
        base09 = oranges[0]["hex"] if oranges else accents[min(5, len(accents)-1)]["hex"]

        # Purple/Magenta (base0E):
        purples = [c for c in accents if 0.70 <= c["h"] <= 0.90]
        base0E = purples[0]["hex"] if purples else accents[min(6, len(accents)-1)]["hex"]

        # Secondary accent (base0F):
        base0F = accents[min(7, len(accents)-1)]["hex"]

        # Guarantee accent contrast against panel background (base01)
        base08 = ensure_min_contrast(base08, base01, target_contrast=3.5)
        base09 = ensure_min_contrast(base09, base01, target_contrast=3.5)
        base0A = ensure_min_contrast(base0A, base01, target_contrast=3.5)
        base0B = ensure_min_contrast(base0B, base01, target_contrast=3.5)
        base0C = ensure_min_contrast(base0C, base01, target_contrast=3.5)
        base0D = ensure_min_contrast(base0D, base01, target_contrast=3.5)
        base0E = ensure_min_contrast(base0E, base01, target_contrast=3.5)
        base0F = ensure_min_contrast(base0F, base01, target_contrast=3.5)

        return {
            "base00": base00,
            "base01": base01,
            "base02": base02,
            "base03": base03,
            "base04": base04,
            "base05": base05,
            "base06": base06,
            "base07": base07,
            "base08": base08,
            "base09": base09,
            "base0A": base0A,
            "base0B": base0B,
            "base0C": base0C,
            "base0D": base0D,
            "base0E": base0E,
            "base0F": base0F,
        }
    except Exception as e:
        print(f"[generate_waybar_stylix] Warning: Could not extract colors from {image_path}: {e}", file=sys.stderr)
        return DEFAULT_BASE16.copy()

import json

def get_cache_path(wallpaper_path):
    cache_dir = Path.home() / ".cache" / "waybar" / "styles"
    cache_dir.mkdir(parents=True, exist_ok=True)
    fname = Path(wallpaper_path).name
    return cache_dir / f"{fname}.css", cache_dir / f"{fname}.json"

def generate_css_for_wallpaper(wallpaper_path):
    css_file, json_file = get_cache_path(wallpaper_path)
    palette = None
    # Regenerate if files missing or wallpaper updated
    if not css_file.exists() or not json_file.exists() or os.path.getmtime(wallpaper_path) > os.path.getmtime(css_file):
        print(f"[generate_waybar_stylix] Generating CSS for wallpaper: {wallpaper_path}", flush=True)
        palette = extract_base16(wallpaper_path)
        css_content = CSS_TEMPLATE.format(**palette)
        with open(css_file, "w") as f:
            f.write(css_content)
        with open(json_file, "w") as f:
            json.dump(palette, f, indent=2)
        print(f"[generate_waybar_stylix] Saved CSS and JSON cache to {css_file.parent}", flush=True)
    else:
        try:
            with open(json_file, "r") as f:
                palette = json.load(f)
            # Invalidate old cache if base00 is out of range (v < 0.08 or v > 0.14) or base03 contrast is below 3.5:1
            base00_v = get_hsv_v(palette.get("base00", "#000000"))
            if base00_v < 0.08 or base00_v > 0.14 or get_contrast(palette.get("base03", "#000000"), palette.get("base01", "#000000")) < 3.5:
                print(f"[generate_waybar_stylix] Regenerating cache for {wallpaper_path}", flush=True)
                palette = extract_base16(wallpaper_path)
                css_content = CSS_TEMPLATE.format(**palette)
                with open(css_file, "w") as f:
                    f.write(css_content)
                with open(json_file, "w") as f:
                    json.dump(palette, f, indent=2)
        except Exception:
            palette = extract_base16(wallpaper_path)
    return css_file, json_file, palette

def generate_thumbnails():
    wp_dir = Path.home() / ".dotfiles" / "wallpapers"
    out_dir = Path.home() / ".cache" / "quickshell" / "thumbnails"
    if not wp_dir.exists():
        print(f"[generate_waybar_stylix] Wallpapers dir {wp_dir} does not exist", flush=True)
        return
    out_dir.mkdir(parents=True, exist_ok=True)
    valid_exts = {".jpg", ".jpeg", ".png", ".webp"}
    print(f"[generate_waybar_stylix] Generating thumbnails in {wp_dir} -> {out_dir}", flush=True)

    # 1. Try native Python PIL
    try:
        from PIL import Image, ImageOps
        count = 0
        for f in wp_dir.iterdir():
            if f.is_file() and f.suffix.lower() in valid_exts:
                out_file = out_dir / f"{f.stem}.jpg"
                if not out_file.exists() or f.stat().st_mtime > out_file.stat().st_mtime:
                    try:
                        im = Image.open(f)
                        thumb = ImageOps.fit(im, (300, 200))
                        thumb.convert("RGB").save(out_file)
                        count += 1
                    except Exception as e:
                        print(f"[generate_waybar_stylix] PIL error for {f.name}: {e}", file=sys.stderr, flush=True)
        print(f"[generate_waybar_stylix] Generated {count} thumbnails via Python PIL", flush=True)
        return
    except ImportError:
        print(f"[generate_waybar_stylix] Native PIL not found in python environment", flush=True)

    # 2. Try CLI tools (magick, convert, ffmpeg)
    has_magick = shutil.which("magick") is not None
    has_convert = shutil.which("convert") is not None
    has_ffmpeg = shutil.which("ffmpeg") is not None

    if has_magick or has_convert or has_ffmpeg:
        tool_name = "magick" if has_magick else ("convert" if has_convert else "ffmpeg")
        print(f"[generate_waybar_stylix] Generating thumbnails using CLI tool: {tool_name}", flush=True)
        count = 0
        for f in wp_dir.iterdir():
            if not f.is_file() or f.suffix.lower() not in valid_exts:
                continue
            out_file = out_dir / f"{f.stem}.jpg"
            if out_file.exists() and f.stat().st_mtime <= out_file.stat().st_mtime:
                continue

            if has_magick:
                subprocess.run(["magick", str(f), "-thumbnail", "300x200^", "-gravity", "center", "-extent", "300x200", str(out_file)], stderr=subprocess.DEVNULL)
            elif has_convert:
                subprocess.run(["convert", str(f), "-thumbnail", "300x200^", "-gravity", "center", "-extent", "300x200", str(out_file)], stderr=subprocess.DEVNULL)
            elif has_ffmpeg:
                subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(f), "-vf", "scale=300:200:force_original_aspect_ratio=increase,crop=300:200", str(out_file)], stderr=subprocess.DEVNULL)
            count += 1
        print(f"[generate_waybar_stylix] Generated {count} thumbnails via {tool_name}", flush=True)
        return

    # 3. Fallback: single-pass nix-shell with python3Packages.pillow
    if shutil.which("nix-shell") is not None:
        print(f"[generate_waybar_stylix] Generating thumbnails via nix-shell -p python3Packages.pillow", flush=True)
        batch_script = (
            "import pathlib; from PIL import Image, ImageOps; "
            "wp_dir = pathlib.Path.home() / '.dotfiles' / 'wallpapers'; "
            "out_dir = pathlib.Path.home() / '.cache' / 'quickshell' / 'thumbnails'; "
            "out_dir.mkdir(parents=True, exist_ok=True); "
            "valid = {'.jpg', '.jpeg', '.png', '.webp'}; "
            "[ImageOps.fit(Image.open(f), (300, 200)).convert('RGB').save(out_dir / f'{f.stem}.jpg') "
            "for f in wp_dir.iterdir() if f.is_file() and f.suffix.lower() in valid "
            "and (not (out_dir / f'{f.stem}.jpg').exists() or f.stat().st_mtime > (out_dir / f'{f.stem}.jpg').stat().st_mtime)]"
        )
        res = subprocess.run(["nix-shell", "-p", "python3Packages.pillow", "--run", f"python3 -c \"{batch_script}\""], capture_output=True, text=True)
        if res.returncode == 0:
            print(f"[generate_waybar_stylix] nix-shell thumbnail generation completed successfully", flush=True)
        else:
            print(f"[generate_waybar_stylix] nix-shell error: {res.stderr}", file=sys.stderr, flush=True)
    else:
        print(f"[generate_waybar_stylix] Error: No suitable thumbnail generation tool found!", file=sys.stderr, flush=True)

def cache_all_wallpapers():
    print("[generate_waybar_stylix] Starting cache-all wallpapers...", flush=True)
    wallpapers_dir = Path.home() / ".dotfiles" / "wallpapers"
    if not wallpapers_dir.exists():
        print(f"[generate_waybar_stylix] Wallpapers dir {wallpapers_dir} does not exist", flush=True)
        return
    valid_exts = {".jpg", ".jpeg", ".png", ".webp"}
    count = 0
    for wp in wallpapers_dir.iterdir():
        if wp.is_file() and wp.suffix.lower() in valid_exts:
            generate_css_for_wallpaper(str(wp))
            count += 1
    print(f"[generate_waybar_stylix] Processed Waybar CSS for {count} wallpapers", flush=True)
    generate_thumbnails()

def apply_terminal_theme(palette):
    try:
        import glob
        seq_file = Path.home() / ".cache" / "terminal" / "sequences"
        wal_seq_file = Path.home() / ".cache" / "wal" / "sequences"
        seq_file.parent.mkdir(parents=True, exist_ok=True)
        wal_seq_file.parent.mkdir(parents=True, exist_ok=True)

        base00 = palette.get("base00", "#1d2021")
        base01 = palette.get("base01", "#282828")
        base02 = palette.get("base02", "#3c3836")
        base03 = palette.get("base03", "#504945")
        base04 = palette.get("base04", "#bdae93")
        base05 = palette.get("base05", "#d5c4a1")
        base06 = palette.get("base06", "#ebdbb2")
        base07 = palette.get("base07", "#fbf1c7")
        base08 = palette.get("base08", "#fb4934")
        base09 = palette.get("base09", "#fe8019")
        base0A = palette.get("base0A", "#fabd2f")
        base0B = palette.get("base0B", "#b8bb26")
        base0C = palette.get("base0C", "#8ec07c")
        base0D = palette.get("base0D", "#83a598")
        base0E = palette.get("base0E", "#d3869b")
        base0F = palette.get("base0F", "#d65d0e")

        seqs = [
            f"\033]10;{base05}\007",
            f"\033]11;{base00}\007",
            f"\033]12;{base05}\007",
        ]

        color_map = {
            0: base00, 1: base08, 2: base0B, 3: base0A, 4: base0D, 5: base0E, 6: base0C, 7: base05,
            8: base03, 9: base08, 10: base0B, 11: base0A, 12: base0D, 13: base0E, 14: base0C, 15: base07,
            16: base09, 17: base0F, 18: base01, 19: base02, 20: base04, 21: base06
        }

        for idx, hex_val in color_map.items():
            seqs.append(f"\033]4;{idx};{hex_val}\007")

        seq_str = "".join(seqs)

        with open(seq_file, "w") as f:
            f.write(seq_str)
        with open(wal_seq_file, "w") as f:
            f.write(seq_str)

        for tty in glob.glob("/dev/pts/[0-9]*"):
            try:
                with open(tty, "w") as f:
                    f.write(seq_str)
            except Exception:
                pass
        print("[generate_waybar_stylix] Terminal dynamic palette applied", flush=True)
    except Exception as e:
        print(f"[generate_waybar_stylix] Error applying terminal theme: {e}", file=sys.stderr, flush=True)

def apply_wallpaper_style(wallpaper_path):
    print(f"[generate_waybar_stylix] Applying style for wallpaper: {wallpaper_path}", flush=True)
    if not wallpaper_path or not os.path.exists(wallpaper_path):
        print(f"[generate_waybar_stylix] Error: Wallpaper path {wallpaper_path} invalid or missing", file=sys.stderr, flush=True)
        return
    css_file, json_file, palette = generate_css_for_wallpaper(wallpaper_path)
    
    target_config = Path.home() / ".config" / "waybar" / "style.css"
    target_config.parent.mkdir(parents=True, exist_ok=True)
    
    with open(css_file, "r") as src, open(target_config, "w") as dst:
        dst.write(src.read())
    print(f"[generate_waybar_stylix] Applied CSS to {target_config}", flush=True)

    print(f"PALETTE_JSON:{json.dumps(palette)}", flush=True)

    apply_terminal_theme(palette)

    # Send SIGUSR2 to Waybar to instantly reload style if running
    try:
        res = subprocess.run(["pkill", "-SIGUSR2", "waybar"], capture_output=True, text=True)
        if res.returncode == 0:
            print("[generate_waybar_stylix] Sent SIGUSR2 to waybar", flush=True)
        else:
            print("[generate_waybar_stylix] Waybar process not running", flush=True)
    except Exception as e:
        print(f"[generate_waybar_stylix] pkill error: {e}", file=sys.stderr, flush=True)

def main():
    parser = argparse.ArgumentParser(description="Waybar Stylix Cache & Reload Tool")
    parser.add_argument("--cache-all", action="store_true", help="Pre-cache Stylix definitions for all wallpapers")
    parser.add_argument("--thumbnails", action="store_true", help="Pre-generate wallpaper thumbnails")
    parser.add_argument("--apply", type=str, help="Apply wallpaper stylix CSS to waybar and refresh")

    args = parser.parse_args()

    if args.cache_all:
        cache_all_wallpapers()

    if args.thumbnails:
        generate_thumbnails()

    if args.apply:
        apply_wallpaper_style(args.apply)

if __name__ == "__main__":
    main()

